### ISSUE TITLE
How to change compression level?

### ISSUE THREAD

**Issue by alantliang** [yjh0502/erl-brotli#5]
Hi, thank you for creating this package. I was wondering how you change the compression level from 1-11? Thanks.

**Comment by yjh0502** [comment]
@alantliang You could use `brotli:encode/2`

**Comment by hauleth** [comment]
Yes, there is a way to pass 2nd argument to `brotli:encode/2` that is a map that can contain `quality` key which is compression level from `0` to `11`.
