### ISSUE TITLE
Maintenance of the project

### ISSUE THREAD

**Issue by hauleth** [yjh0502/erl-brotli#8]
Hi @yjh0502, I have tried to contact you via email (about a month ago), but I haven't received any response, so I will request here as well.

---

Hi, I have spotted that you have created Erlang library to provide API for Brotli compression. I allowed myself to provide [few improvements][1] and there is now a question - would you prefer to pass maintaining that library to someone else (I am willing to do so) or I should push these changes up to your repository? I could also handle the Hex.pm package maintenance.

[1]: https://github.com/yjh0502/erl-brotli/compare/master...hauleth:master

The improvements added so far are:

- expanding test suite, property testing, more examples, etc.
- GitHub Actions for CI
- decompression support
- streaming API support
- cleanup of C code
- better errors
- support for more configuration options
- dirty schedulers configuration for CPU intensive tasks
- code formatting
- coverage reporting

I used this library in [Phoenix Brotli Compressor](https://github.com/hauleth/phoenix_brotli_compressor) library for Phoenix 1.6 and I would be willing to pick up on maintenance from You on Hex.pm. Would you be willing to pass the torch to me?

**Comment by yjh0502** [comment]
@hauleth Could you share your hex.pm username so I could give you a permission?

**Comment by yjh0502** [comment]
@hauleth I gave you an hex.pm access, too. Although the repository is not maintained, It is actively used on one of our production app for several years, so I'm a bit afraid of transferring the repository. Could we try those changes on this repository?

**Comment by hauleth** [comment]
> @hauleth I gave you an hex.pm access, too. Although the repository is not maintained, It is actively used on one of our production app for several years, so I'm a bit afraid of transferring the repository. Could we try those changes on this repository?


No problem. I can manage it there and we can think about transferring the repository in more or less defined future.

--

Łukasz Niemier
***@***.***

**Comment by yjh0502** [comment]
Thanks!
